[package]
name = "const-str-proc-macro"
version = "0.3.0-dev"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2018"
description = "compile-time string operations"
license = "MIT"
repository = "https://github.com/Nugine/const-str"
keywords = ["string", "const", "proc-macro"]
categories = ["text-processing", "no-std"]
readme = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc_macro = true

[dependencies]
syn = "1.0.40"
quote = "1.0.7"
regex = { version = "1.3.9", optional = true }
http = { version = "0.2.1", optional = true }
proc-macro2 = "1.0.21"
heck = { version = "0.3.1", optional = true }
