[package]
name = "const-str"
version = "0.2.1"
authors = ["Nugine <nugine@foxmail.com>"]
edition = "2018"
description = "compile-time string operations"
license = "MIT"
repository = "https://github.com/Nugine/const-str"
keywords = ["string", "const", "proc-macro"]
categories = ["text-processing", "no-std"]
readme = "../README.md"

[features]
default = []
verify-regex = ["const-str-proc-macro/regex"]
verify-http = ["const-str-proc-macro/http"]
case = ["const-str-proc-macro/heck"]
all = ["verify-regex", "verify-http", "case"]

[package.metadata.docs.rs]
all-features = true

[dependencies.const-str-proc-macro]
version = "=0.2.1"
path = "../const-str-proc-macro"

[dev-dependencies]
regex = "1.3.9"
http = "0.2.1"
